### ISSUE TITLE
关于XJTU_gearbox.py中dataset_save

### ISSUE THREAD

**Issue by HJPU** [yanshen0210/LiConvFormer-a-lightweight-fault-diagnosis-framework#6]
代码中list_data = [data1, lab1]；data1中数据维度为[2,1024]，如何与lab1拼接，data1中数据维度[2,1024],s是否一行表示x方向的振动数据，一行表示y方向的振动数据，如何将两个方向的振动数据进行合成为您论文中1024维度的输入数据

**Comment by yanshen0210** [comment]
如你理解的，data1就是代表两个通道的数据。[2,1024]代表的是一个样本，故对应一个标签lab1即可，故data1与lab1不需要进行拼接操作。

HJPU ***@***.***> 于2024年3月17日周日 15:33写道：
