### ISSUE TITLE
关于渥太华数据集转换问题

### ISSUE THREAD

**Issue by syw722** [yanshen0210/LiConvFormer-a-lightweight-fault-diagnosis-framework#7]
你好，在运行代码的时候出现了如下错误
setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (6, 3000) + inhomogeneous part.
想问一下解决方案

**Comment by yanshen0210** [comment]
把 numpy 版本改为1.22.0尝试下

syw722 ***@***.***> 于2024年7月9日周二 17:26写道：
